POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "root@gmail.com",
  "password": "secret123"
}

###

POST http://localhost:8080/operations/execute
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290QGdtYWlsLmNvbSIsImV4cCI6MTcxNjUwODk1N30.gt3UmQceWgbkgUmIn6HvJceXCDAKQ5_gJVyhHdg8y8o

{
  "operationType": "square_root",
  "number1": 10,
  "number2": 5
}

###
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290QGdtYWlsLmNvbSIsImV4cCI6MTcxNjUwODk1N30.gt3UmQceWgbkgUmIn6HvJceXCDAKQ5_gJVyhHdg8y8o

###
GET http://localhost:8080/records/mine
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290QGdtYWlsLmNvbSIsImV4cCI6MTcxNjUwOTg1Mn0.mrY5WkHgarvuVO8hQ6AODWSDZ2s-0T8q3G1nq0lahEs

###
POST http://localhost:8080/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGJlcnRvLmNyY3UxNUBnbWFpbC5jb20ifQ.etHe0_4Y1lTLreqjmWJtua9NagdPaTBwBcrYb-U0bLs


